title: Drew Chibib 
description: mostly for publishing things i've written. does also contain books and essays i find compelling, people whose work i follow, and questions i find either important, entertaining, or both.
theme: just-the-docs

url: https://drewchibib.github.io

